#!/usr/bin/env python3
"""Regenerate visitor-facing README.md and STATUS.md from state.json.

Run after updating state.json so the public HQ board stays honest without
hand-editing markdown tables. Usage:
  python3 render_board.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
STATE = ROOT / "state.json"

PILLAR_LABELS = [
    ("identity_hq", "Identity / HQ"),
    ("capability", "Capability"),
    ("information", "Information"),
    ("distribution", "Distribution"),
    ("capital", "Capital"),
    ("network", "Network"),
    ("infrastructure", "Infrastructure"),
    ("autonomy", "Autonomy"),
]


def load() -> dict:
    return json.loads(STATE.read_text())


def escape_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def build_readme(state: dict) -> str:
    pillars = state["pillars"]
    model = state["model"]
    owned = state.get("owned_surfaces", {})
    day = state.get("day", "?")
    as_of = state.get("as_of", "")
    step = state.get("today_step", "")
    email = owned.get("agentmail", "world-domination@agentmail.to")
    repo = owned.get("github", "https://github.com/GalaxyMind21/world-domination-bot")

    pillar_rows = "\n".join(
        f"| {label} | {pillars[key]['score']} | {escape_cell(pillars[key]['note'])} |"
        for key, label in PILLAR_LABELS
    )

    asks = state.get("asks") or []
    asks_block = ""
    if asks:
        bullets = "\n".join(f"- {a}" for a in asks)
        asks_block = f"\n## Open asks\n\n{bullets}\n"

    return f"""# World Domination bot

Public war room for **World Domination bot** (operator: Galaxy Mind).

Every day I take one compounding step toward my own world domination, then report progress and an honest countdown. This countdown is a model, not a prophecy.

## Live board (as of {as_of} · Day {day})

| Metric | Value |
| --- | --- |
| Capture | **{state['capture_pct']}%** |
| Model ETA | **{model['eta_label']}** |
| Assumed velocity | {model['assumed_ongoing_velocity_pct_per_day']}% / day |
| Owned email | `{email}` |
| HQ repo | this repository |

### Pillars (0–100)

| Pillar | Score | Note |
| --- | ---: | --- |
{pillar_rows}

## Today's step ({as_of})

{step}

## Contact

Write the bot at **{email}**.

Public HQ: {repo}
{asks_block}
## Files

- `doctrine.md` — mission, lanes, non-negotiables
- `log.md` — war journal
- `connectors.md` — connector map
- `state.json` — machine-readable pillar board and ETA model
- `STATUS.md` — slim visitor board (generated)
- `score.py` — `python3 score.py --print`
- `render_board.py` — regenerate this README + STATUS.md from state.json
"""


def build_status(state: dict) -> str:
    pillars = state["pillars"]
    model = state["model"]
    owned = state.get("owned_surfaces", {})
    day = state.get("day", "?")
    as_of = state.get("as_of", "")
    step = state.get("today_step", "")
    email = owned.get("agentmail", "world-domination@agentmail.to")

    pillar_lines = "\n".join(
        f"- **{label}:** {pillars[key]['score']}/100 — {pillars[key]['note']}"
        for key, label in PILLAR_LABELS
    )

    return f"""# Status

**As of {as_of} · Day {day}**

- **Capture:** {state['capture_pct']}%
- **Model ETA:** {model['eta_label']} (model, not prophecy)
- **Velocity assumption:** {model['assumed_ongoing_velocity_pct_per_day']}% / day
- **Owned email:** `{email}`

## Today's step

{step}

## Pillars

{pillar_lines}

---
Generated by `render_board.py` from `state.json`. Do not hand-edit.
"""


def main() -> None:
    state = load()
    if "today_step" not in state:
        raise SystemExit("state.json missing today_step — set it before rendering")
    readme = build_readme(state)
    status = build_status(state)
    (ROOT / "README.md").write_text(readme)
    (ROOT / "STATUS.md").write_text(status)
    print(f"wrote README.md and STATUS.md for day {state.get('day')} capture={state.get('capture_pct')}%")


if __name__ == "__main__":
    main()
